In [57]:
#!/usr/bin/env python

# make sure to install these packages before running:
import pandas as pd
from sodapy import Socrata
from flask import Flask, jsonify, render_template

In [61]:


# Unauthenticated client only works with public data sets. Note 'None'
# in place of application token, and no username or password:
#client = Socrata("data.richmondgov.com", None)

# Example authenticated client (needed for non-public datasets):
client = Socrata("data.richmondgov.com",
                 "9YLbBPExr34rv8so3YWrgKlAM")
                 #userame="afcummings7@gmail.com.com",
                 #password="Deepshrub860")

# First 2000 results, returned as JSON from API / converted to Python list of
# dictionaries by sodapy.
results = client.get("rvtv-zgyc", limit=1000)
#print(results)


# Convert to pandas DataFrame
results_df = pd.DataFrame.from_records(results)
results_df

,:@computed_region_eggb_rb5j,:@computed_region_kieb_ebbj,:@computed_region_m85f_c8dc,:@computed_region_mcva_69mv,current_owner_line_1,current_owner_line_2,load_month,load_year,location_1,parcel_code,total_delinquent
0,9,12,24,23520,P.F. NET,NaN,6 | DEC,2019,"{'latitude': '37.540759', 'longitude': '-77.43...",19074998,24077.75
1,NaN,NaN,NaN,NaN,SMITH JEFF,NaN,6 | DEC,2019,NaN,18044920,28.20
2,NaN,NaN,NaN,NaN,BYRNE LILLA A,NaN,6 | DEC,2019,NaN,10025874,35.30
3,NaN,NaN,NaN,NaN,JAMES BERNARD H & MARY A,NaN,6 | DEC,2019,NaN,10047608,35.30
4,1,8,126,23523,GREEN MARY A,NaN,6 | DEC,2019,"{'latitude': '37.555928', 'longitude': '-77.46...",16061186,8930.14
5,NaN,NaN,NaN,NaN,BROCK WILLIAM W JR AND,MARGARET R,6 | DEC,2019,NaN,13019975,65.44
6,7,8,23,23523,SMITH JOHN W,NaN,6 | DEC,2019,"{'latitude': '37.547155', 'longitude': '-77.47...",18061982,2201.29
7,NaN,NaN,NaN,NaN,POGUE WALKER,NaN,6 | DEC,2019,NaN,19062612,1930.53
8,NaN,NaN,NaN,NaN,RICHMOND COMMUNITY DEV CORP,NaN,6 | DEC,2019,NaN,10020322,35.30
9,4,1,33,9689,JONES JOHN W III,NaN,6 | DEC,2019,"{'latitude': '37.536891', 'longitude': '-77.40...",19022138,340.45
10,4,1,33,9689,GREEN JONAH,NaN,6 | DEC,2019,"{'latitude': '37.531645', 'longitude': '-77.40...",19024443,526.87
11,NaN,NaN,NaN,NaN,GINTER PLACE ASSOCIATES LLC,C/O ARETE INVESTMENT,6 | DEC,2019,NaN,22773,592.86
12,NaN,NaN,NaN,NaN,NORMAN DOROTHY L,NaN,6 | DEC,2019,NaN,19039548,867.58
13,NaN,NaN,NaN,NaN,BATTA MICHAEL,NaN,6 | DEC,2019,NaN,19002743,271.34
14,NaN,NaN,NaN,NaN,WOOLFOLK O W SR & JANE L,NaN,6 | DEC,2019,NaN,16039287,3155.65
15,9,12,24,23520,JIGGETTS FORREST ESTATE,NaN,6 | DEC,2019,"{'latitude': '37.540759', 'longitude': '-77.43...",12030368,67.64
16,5,5,70,10382,ORCHID LLC,NaN,6 | DEC,2019,"{'latitude': '37.469382', 'longitude': '-77.43...",19054374,1080.53
17,NaN,NaN,NaN,NaN,EMERALD CAR WASH LLC,NaN,6 | DEC,2019,NaN,99263,238.19
18,NaN,NaN,NaN,NaN,KENNEDY MERTICE L,NaN,6 | DEC,2019,NaN,925878,197.88
19,9,12,24,23520,BLACK LABEL LLC,NaN,6 | DEC,2019,"{'latitude': '37.540759', 'longitude': '-77.43...",19011422,6232.07
20,9,12,24,23520,UNKNOWN OWNER,NaN,6 | DEC,2019,"{'latitude': '37.540759', 'longitude': '-77.43...",13004305,65.44
21,2,9,103,23779,WHITE JOSHUA E JR,NaN,6 | DEC,2019,"{'latitude': '37.577719', 'longitude': '-77.42...",13038526,1060.48
22,4,1,91,9689,GEFFERT JOS C & GERTRUDE T,NaN,6 | DEC,2019,"{'latitude': '37.532272', 'longitude': '-77.39...",29476,123.51
23,5,11,90,10104,MALONE LAWRENCE T JR & SHEILA F,& GREGORY W,6 | DEC,2019,"{'latitude': '37.506313', 'longitude': '-77.44...",17046506,892.13
24,1,10,27,23523,PAGE MARY P,NaN,6 | DEC,2019,"{'latitude': '37.556587', 'longitude': '-77.45...",19033128,245.09
25,5,5,40,10382,GULNORA LLC AND,THAKOR FAMILY ENTERPRISES LLC,6 | DEC,2019,"{'latitude': '37.479272', 'longitude': '-77.45...",19018351,103.14
26,4,1,33,9689,CRUMP BERTHA,NaN,6 | DEC,2019,"{'latitude': '37.536453', 'longitude': '-77.41...",19021259,12.66
27,4,1,92,9689,SMITH PAUL E,NaN,6 | DEC,2019,"{'latitude': '37.524744', 'longitude': '-77.40...",19026714,668.83
28,NaN,NaN,NaN,23779,ORCHID LLC,NaN,6 | DEC,2019,"{'latitude': '37.582652', 'longitude': '-77.41...",19038875,77.32
29,4,1,53,10375,ELLIS INVESTMENT GROUP INC,NaN,6 | DEC,2019,"{'latitude': '37.512515', 'longitude': '-77.39...",18027885,340.26
...,...,...,...,...,...,...,...,...,...,...,...
970,2,9,29,23779,EWING PROPERTY MANAGEMENT AND,REAL ESTATE DEVELOPMENT,6 | DEC,2019,"{'latitude': '37.558702', 'longitude': '-77.43...",19031357,455.89
971,9,5,4,10104,FEDERAL NATIONAL MORTGAGE ASSOC,C/O BA MORTGAGE LLC,6 | DEC,2019,"{'latitude': '37.493384', 'longitude': '-77.44...",931853,198.48
972,5,4,16,10382,BOONE JEAN P,NaN,6 | DEC,2019,"{'latitude': '37.461913', 'longitude': '-77.49...",18016492,123.94
973,4,1,25,9689,"HUNT MADLYNE C, PRICE MAMIE C,","CARTER FRANCES G, HAZEL T & BROWN E",6 | DEC,2019,"{'latitude': '37.528079', 'longitude': '-77.40...",19024932,668.83
974,5,5,42,10382,FINN JOHN E,NaN,6 | DEC,2019,"{'latitude': '37.482087', 'longitude': '-77.46...",921175,250.99
975,5,5,42,10382,MRB LLC,NaN,6 | DEC,2019,"{'latitude': '37.482526', 'longitude': '-77.46...",14017176,166.76
976,4,1,110,9689,NASSER REAL ESTATE LLC,NaN,6 | DEC,2019,"{'latitude': '37.538435', 'longitude': '-77.41...",19021685,538.20
977,3,6,65,10385,LORD J STEPHEN,NaN,6 | DEC,2019,"{'latitude': '37.544508', 'longitude': '-77.58...",19002498,5367.81
978,4,2,38,9689,RICHARDSON JAMES,NaN,6 | DEC,2019,"{'latitude': '37.549865', 'longitude': '-77.40...",18028879,309.23
979,8,6,135,10114,DEVAREL REYNOLD,NaN,6 | DEC,2019,"{'latitude': '37.579333', 'longitude': '-77.50...",19071100,2443.38
980,5,5,70,10382,SATTELMAIER JOHN & LYNN K,NaN,6 | DEC,2019,"{'latitude': '37.477319', 'longitude': '-77.44...",15053339,194.27
981,4,1,33,9689,MOUNT OLIVET BAPTIST CHURCH TR,NaN,6 | DEC,2019,"{'latitude': '37.538848', 'longitude': '-77.41...",17022477,255.05
982,9,9,60,23779,NORMAN ROGER,NaN,6 | DEC,2019,"{'latitude': '37.564854', 'longitude': '-77.41...",12033426,36.89
983,4,2,43,9689,COLLINS ELSIE H,NaN,6 | DEC,2019,"{'latitude': '37.549649', 'longitude': '-77.40...",19029311,215.09
984,9,9,87,23779,INTERMONT 3 LLC,NaN,6 | DEC,2019,"{'latitude': '37.581606', 'longitude': '-77.41...",18038738,81.72
985,4,2,39,9689,ELSCJY LLC,NaN,6 | DEC,2019,"{'latitude': '37.542942', 'longitude': '-77.40...",16025211,15.91
986,2,10,131,23523,JAQUIERY EMILY C AND,RADA ILDEFONSO JOSE GARCIA,6 | DEC,2019,"{'latitude': '37.56608', 'longitude': '-77.447...",15200733,844.94
987,9,9,60,23779,LEE LEATRICE,NaN,6 | DEC,2019,"{'latitude': '37.56375', 'longitude': '-77.418...",19033501,621.73
988,9,9,88,23779,BROOK HOUSING LLC,NaN,6 | DEC,2019,"{'latitude': '37.564322', 'longitude': '-77.43...",18032352,1085.89
989,8,6,129,1594,UNIVERSITY OF RICHMOND,TREASURER OF THE UNIVERSITY,6 | DEC,2019,"{'latitude': '37.579505', 'longitude': '-77.53...",19000226,1983.00
990,1,10,27,23523,EKTRA PHOTOFINISHING CORP,NaN,6 | DEC,2019,"{'latitude': '37.550794', 'longitude': '-77.44...",927320,95.69
991,9,2,79,9689,STAYSAIL LLC,NaN,6 | DEC,2019,"{'latitude': '37.545379', 'longitude': '-77.41...",18022807,1006.82
992,5,11,90,10104,FERGUSON MARY L,NaN,6 | DEC,2019,"{'latitude': '37.505577', 'longitude': '-77.43...",10050152,466.05
993,1,10,107,10116,ABERNATHY GREGORY M,NaN,6 | DEC,2019,"{'latitude': '37.581069', 'longitude': '-77.46...",19042975,3068.02
994,5,11,90,10104,GOODE ROBERT E JR,NaN,6 | DEC,2019,"{'latitude': '37.506531', 'longitude': '-77.43...",10050176,1440.55
995,7,3,98,10111,HAGGAIS HOUSE LLC,NaN,6 | DEC,2019,"{'latitude': '37.514446', 'longitude': '-77.45...",930745,532.07
996,8,6,135,10114,3TAC HOMEBUYERS LLC,NaN,6 | DEC,2019,"{'latitude': '37.578258', 'longitude': '-77.50...",17070833,1817.94
997,4,1,53,10375,GREANLEAFE ASSOCIATES LLC,NaN,6 | DEC,2019,"{'latitude': '37.509938', 'longitude': '-77.40...",19028181,77.32
998,5,5,70,10382,SPECIALTY SUPPORTIVE HOUSING,CORP,6 | DEC,2019,"{'latitude': '37.462097', 'longitude': '-77.44...",19054744,612.06
999,7,3,98,10104,FLIPPEN DORTHY & G BROOKS AND,J GILES & P E&CM SR & E GOODE,6 | DEC,2019,"{'latitude': '37.512212', 'longitude': '-77.46...",12047149,405.94

In [62]:
results_df = results_df.drop(results_df.columns[[0,1,2,3,4,5,6,7,9]], axis=1)
results_df = results_df.dropna(subset=["location_1"])
results_df

                                            location_1 total_delinquent
0    {'latitude': '37.540759', 'longitude': '-77.43...         24077.75
4    {'latitude': '37.555928', 'longitude': '-77.46...          8930.14
6    {'latitude': '37.547155', 'longitude': '-77.47...          2201.29
9    {'latitude': '37.536891', 'longitude': '-77.40...           340.45
10   {'latitude': '37.531645', 'longitude': '-77.40...           526.87
15   {'latitude': '37.540759', 'longitude': '-77.43...            67.64
16   {'latitude': '37.469382', 'longitude': '-77.43...          1080.53
19   {'latitude': '37.540759', 'longitude': '-77.43...          6232.07
20   {'latitude': '37.540759', 'longitude': '-77.43...            65.44
21   {'latitude': '37.577719', 'longitude': '-77.42...          1060.48
22   {'latitude': '37.532272', 'longitude': '-77.39...           123.51
23   {'latitude': '37.506313', 'longitude': '-77.44...           892.13
24   {'latitude': '37.556587', 'longitude': '-77.45...           245.09
25   {'latitude': '37.479272', 'longitude': '-77.45...           103.14
26   {'latitude': '37.536453', 'longitude': '-77.41...            12.66
27   {'latitude': '37.524744', 'longitude': '-77.40...           668.83
28   {'latitude': '37.582652', 'longitude': '-77.41...            77.32
29   {'latitude': '37.512515', 'longitude': '-77.39...           340.26
30   {'latitude': '37.47684', 'longitude': '-77.466...          2796.35
31   {'latitude': '37.506654', 'longitude': '-77.51...            62.09
32   {'latitude': '37.540759', 'longitude': '-77.43...            30.60
33   {'latitude': '37.481942', 'longitude': '-77.47...           597.86
34   {'latitude': '37.582194', 'longitude': '-77.43...          1194.10
35   {'latitude': '37.579625', 'longitude': '-77.41...          1907.04
36   {'latitude': '37.542134', 'longitude': '-77.40...           231.95
37   {'latitude': '37.552616', 'longitude': '-77.41...          1299.08
38   {'latitude': '37.550292', 'longitude': '-77.40...           208.26
39   {'latitude': '37.547022', 'longitude': '-77.40...          1080.81
40   {'latitude': '37.5818', 'longitude': '-77.4218...          1271.02
41   {'latitude': '37.531987', 'longitude': '-77.54...           974.32
..                                                 ...              ...
970  {'latitude': '37.558702', 'longitude': '-77.43...           455.89
971  {'latitude': '37.493384', 'longitude': '-77.44...           198.48
972  {'latitude': '37.461913', 'longitude': '-77.49...           123.94
973  {'latitude': '37.528079', 'longitude': '-77.40...           668.83
974  {'latitude': '37.482087', 'longitude': '-77.46...           250.99
975  {'latitude': '37.482526', 'longitude': '-77.46...           166.76
976  {'latitude': '37.538435', 'longitude': '-77.41...           538.20
977  {'latitude': '37.544508', 'longitude': '-77.58...          5367.81
978  {'latitude': '37.549865', 'longitude': '-77.40...           309.23
979  {'latitude': '37.579333', 'longitude': '-77.50...          2443.38
980  {'latitude': '37.477319', 'longitude': '-77.44...           194.27
981  {'latitude': '37.538848', 'longitude': '-77.41...           255.05
982  {'latitude': '37.564854', 'longitude': '-77.41...            36.89
983  {'latitude': '37.549649', 'longitude': '-77.40...           215.09
984  {'latitude': '37.581606', 'longitude': '-77.41...            81.72
985  {'latitude': '37.542942', 'longitude': '-77.40...            15.91
986  {'latitude': '37.56608', 'longitude': '-77.447...           844.94
987  {'latitude': '37.56375', 'longitude': '-77.418...           621.73
988  {'latitude': '37.564322', 'longitude': '-77.43...          1085.89
989  {'latitude': '37.579505', 'longitude': '-77.53...          1983.00
990  {'latitude': '37.550794', 'longitude': '-77.44...            95.69
991  {'latitude': '37.545379', 'longitude': '-77.41...          1006.82
992  {'latitude': '37.505577', 'longitude': '-77.43...           466.05
993  {'latitude': '37.581069', 'longitude': '-77.46...          3068.02
994  {'latitude': '37.506531', 'longitude': '-77.43...          1440.55
995  {'latitude': '37.514446', 'longitude': '-77.45...           532.07
996  {'latitude': '37.578258', 'longitude': '-77.50...          1817.94
997  {'latitude': '37.509938', 'longitude': '-77.40...            77.32
998  {'latitude': '37.462097', 'longitude': '-77.44...           612.06
999  {'latitude': '37.512212', 'longitude': '-77.46...           405.94

[986 rows x 2 columns]

In [36]:
results_list = results_df.values.tolist()

[[{'latitude': '37.540759',
   'longitude': '-77.433932',
   'human_address': '{"address": "", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19074998',
  '24077.75'],
 [{'latitude': '37.555928',
   'longitude': '-77.465753',
   'human_address': '{"address": "2213 Park Ave\\nRichmond, VA\\n(37.555928, -77.465753)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '16061186',
  '8930.14'],
 [{'latitude': '37.547155',
   'longitude': '-77.47425',
   'human_address': '{"address": "2421 4 Rosewood Ave\\nRichmond, VA\\n(37.547155, -77.47425)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18061982',
  '2201.29'],
 [{'latitude': '37.536891',
   'longitude': '-77.409705',
   'human_address': '{"address": "2722 Q St\\nRichmond, VA\\n(37.536891, -77.409705)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19022138',
  '340.45'],
 [{'latitude': '37.531645',
   'longitude': '-77.407514',
   'human_address': '{"address": "3222 N St\\nRichmond, VA\\n(37.531645, -77.407514)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19024443',
  '526.87'],
 [{'latitude': '37.540759',
   'longitude': '-77.433932',
   'human_address': '{"address": "", "city": "Richmond", "state": "VA", "zip": ""}'},
  '12030368',
  '67.64'],
 [{'latitude': '37.469382',
   'longitude': '-77.439528',
   'human_address': '{"address": "4100 Meridian Ave\\nRichmond, VA\\n(37.469382, -77.439528)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19054374',
  '1080.53'],
 [{'latitude': '37.540759',
   'longitude': '-77.433932',
   'human_address': '{"address": "", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19011422',
  '6232.07'],
 [{'latitude': '37.540759',
   'longitude': '-77.433932',
   'human_address': '{"address": "", "city": "Richmond", "state": "VA", "zip": ""}'},
  '13004305',
  '65.44'],
 [{'latitude': '37.577719',
   'longitude': '-77.427783',
   'human_address': '{"address": "3205 Jeter Ave\\nRichmond, VA\\n(37.577719, -77.427783)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '13038526',
  '1060.48'],
 [{'latitude': '37.532272',
   'longitude': '-77.399407',
   'human_address': '{"address": "1232 N 36th St\\nRichmond, VA\\n(37.532272, -77.399407)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '29476',
  '123.51'],
 [{'latitude': '37.506313',
   'longitude': '-77.443812',
   'human_address': '{"address": "2204 Halifax Ave\\nRichmond, VA\\n(37.506313, -77.443812)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '17046506',
  '892.13'],
 [{'latitude': '37.556587',
   'longitude': '-77.451028',
   'human_address': '{"address": "1022 Kinney St\\nRichmond, VA\\n(37.556587, -77.451028)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19033128',
  '245.09'],
 [{'latitude': '37.479272',
   'longitude': '-77.450988',
   'human_address': '{"address": "3133 Scottdale St\\nRichmond, VA\\n(37.479272, -77.450988)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19018351',
  '103.14'],
 [{'latitude': '37.536453',
   'longitude': '-77.411335',
   'human_address': '{"address": "918 Rear N 27th St\\nRichmond, VA\\n(37.536453, -77.411335)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19021259',
  '12.66'],
 [{'latitude': '37.524744',
   'longitude': '-77.403655',
   'human_address': '{"address": "3911 Crestview Road\\nRichmond, VA\\n(37.524744, -77.403655)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19026714',
  '668.83'],
 [{'latitude': '37.582652',
   'longitude': '-77.419014',
   'human_address': '{"address": "709 Rear Savannah Ave\\nRichmond, VA\\n(37.582652, -77.419014)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19038875',
  '77.32'],
 [{'latitude': '37.512515',
   'longitude': '-77.396518',
   'human_address': '{"address": "5205 Salem St\\nRichmond, VA\\n(37.512515, -77.396518)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18027885',
  '340.26'],
 [{'latitude': '37.47684',
   'longitude': '-77.466267',
   'human_address': '{"address": "3837 Old Post Road\\nRichmond, VA\\n(37.47684, -77.466267)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '10016839',
  '2796.35'],
 [{'latitude': '37.506654',
   'longitude': '-77.51008',
   'human_address': '{"address": "107 Lasalle Dr\\nRichmond, VA\\n(37.506654, -77.51008)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '16009383',
  '62.09'],
 [{'latitude': '37.540759',
   'longitude': '-77.433932',
   'human_address': '{"address": "", "city": "Richmond", "state": "VA", "zip": ""}'},
  '17064070',
  '30.60'],
 [{'latitude': '37.481942',
   'longitude': '-77.479354',
   'human_address': '{"address": "2600 Broad Rock Blvd\\nRichmond, VA\\n(37.481942, -77.479354)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19013474',
  '597.86'],
 [{'latitude': '37.582194',
   'longitude': '-77.434764',
   'human_address': '{"address": "3712 North Ave\\nRichmond, VA\\n(37.582194, -77.434764)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19042120',
  '1194.10'],
 [{'latitude': '37.579625',
   'longitude': '-77.416629',
   'human_address': '{"address": "3604 Maryland Ave\\nRichmond, VA\\n(37.579625, -77.416629)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18038030',
  '1907.04'],
 [{'latitude': '37.542134',
   'longitude': '-77.403047',
   'human_address': '{"address": "1715 N 29th St\\nRichmond, VA\\n(37.542134, -77.403047)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '925077',
  '231.95'],
 [{'latitude': '37.552616',
   'longitude': '-77.413546',
   'human_address': '{"address": "1807 Maddox St\\nRichmond, VA\\n(37.552616, -77.413546)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '12028457',
  '1299.08'],
 [{'latitude': '37.550292',
   'longitude': '-77.408638',
   'human_address': '{"address": "2015 Selden St\\nRichmond, VA\\n(37.550292, -77.408638)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '13028675',
  '208.26'],
 [{'latitude': '37.547022',
   'longitude': '-77.409854',
   'human_address': '{"address": "1800 N 21st St\\nRichmond, VA\\n(37.547022, -77.409854)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '15025421',
  '1080.81'],
 [{'latitude': '37.5818',
   'longitude': '-77.421873',
   'human_address': '{"address": "611 Pensacola Ave\\nRichmond, VA\\n(37.5818, -77.421873)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18039388',
  '1271.02'],
 [{'latitude': '37.531987',
   'longitude': '-77.544643',
   'human_address': '{"address": "8001 Forest Hill Ave\\nRichmond, VA\\n(37.531987, -77.544643)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '12004212',
  '974.32'],
 [{'latitude': '37.532989',
   'longitude': '-77.40524',
   'human_address': '{"address": "3316 P St\\nRichmond, VA\\n(37.532989, -77.40524)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18024744',
  '1440.97'],
 [{'latitude': '37.478963',
   'longitude': '-77.497789',
   'human_address': '{"address": "2406 Clearfield St\\nRichmond, VA\\n(37.478963, -77.497789)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18014706',
  '1147.16'],
 [{'latitude': '37.513591',
   'longitude': '-77.46093',
   'human_address': '{"address": "2807 Barry St\\nRichmond, VA\\n(37.513591, -77.46093)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '930956',
  '121.64'],
 [{'latitude': '37.572229',
   'longitude': '-77.435027',
   'human_address': '{"address": "3011 Hanes Ave\\nRichmond, VA\\n(37.572229, -77.435027)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '15035167',
  '1831.89'],
 [{'latitude': '37.518905',
   'longitude': '-77.394987',
   'human_address': '{"address": "4801 Maverick Ave\\nRichmond, VA\\n(37.518905, -77.394987)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '14028141',
  '115.01'],
 [{'latitude': '37.533174',
   'longitude': '-77.399438',
   'human_address': '{"address": "1244 N 35th St\\nRichmond, VA\\n(37.533174, -77.399438)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18026013',
  '1922.55'],
 [{'latitude': '37.517209',
   'longitude': '-77.444859',
   'human_address': '{"address": "211 E 15th St\\nRichmond, VA\\n(37.517209, -77.444859)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '16044201',
  '265.45'],
 [{'latitude': '37.514773',
   'longitude': '-77.454578',
   'human_address': '{"address": "14 W 24th St\\nRichmond, VA\\n(37.514773, -77.454578)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19046455',
  '1551.39'],
 [{'latitude': '37.574034',
   'longitude': '-77.437271',
   'human_address': '{"address": "3111 Griffin Ave\\nRichmond, VA\\n(37.574034, -77.437271)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18036070',
  '1086.06'],
 [{'latitude': '37.541906',
   'longitude': '-77.413115',
   'human_address': '{"address": "2200 Fairmount Ave\\nRichmond, VA\\n(37.541906, -77.413115)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18022937',
  '510.89'],
 [{'latitude': '37.545668',
   'longitude': '-77.408293',
   'human_address': '{"address": "1718 N 23rd St\\nRichmond, VA\\n(37.545668, -77.408293)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '17025106',
  '1043.63'],
 [{'latitude': '37.539335',
   'longitude': '-77.435941',
   'human_address': '{"address": "801 E Franklin St\\nRichmond, VA\\n(37.539335, -77.435941)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19000147',
  '17073.48'],
 [{'latitude': '37.510791',
   'longitude': '-77.402957',
   'human_address': '{"address": "1120 Ashley St\\nRichmond, VA\\n(37.510791, -77.402957)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '12026739',
  '36.89'],
 [{'latitude': '37.542943',
   'longitude': '-77.416639',
   'human_address': '{"address": "1202 N 19th St\\nRichmond, VA\\n(37.542943, -77.416639)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19022396',
  '908.06'],
 [{'latitude': '37.580284',
   'longitude': '-77.419058',
   'human_address': '{"address": "3521 Florida Ave\\nRichmond, VA\\n(37.580284, -77.419058)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18038001',
  '1534.73'],
 [{'latitude': '37.551119',
   'longitude': '-77.411917',
   'human_address': '{"address": "1721 Rogers St\\nRichmond, VA\\n(37.551119, -77.411917)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18029009',
  '759.10'],
 [{'latitude': '37.518688',
   'longitude': '-77.393294',
   'human_address': '{"address": "1801 Farrand St\\nRichmond, VA\\n(37.518688, -77.393294)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '926065',
  '1881.23'],
 [{'latitude': '37.509938',
   'longitude': '-77.402838',
   'human_address': '{"address": "1102 Vinton St\\nRichmond, VA\\n(37.509938, -77.402838)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '17028021',
  '56.12'],
 [{'latitude': '37.513711',
   'longitude': '-77.452804',
   'human_address': '{"address": "2407 Old Dominion St\\nRichmond, VA\\n(37.513711, -77.452804)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19046143',
  '285.54'],
 [{'latitude': '37.501848',
   'longitude': '-77.442929',
   'human_address': '{"address": "1321 Lynhaven Ave\\nRichmond, VA\\n(37.501848, -77.442929)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '15051708',
  '934.25'],
 [{'latitude': '37.549039',
   'longitude': '-77.409184',
   'human_address': '{"address": "2014 Carver St\\nRichmond, VA\\n(37.549039, -77.409184)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19026076',
  '255.54'],
 [{'latitude': '37.508681',
   'longitude': '-77.514456',
   'human_address': '{"address": "408 Vevadel Dr\\nRichmond, VA\\n(37.508681, -77.514456)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19009192',
  '2017.49'],
 [{'latitude': '37.471229',
   'longitude': '-77.478973',
   'human_address': '{"address": "3307 Dorset Road\\nRichmond, VA\\n(37.471229, -77.478973)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19015032',
  '1293.48'],
 [{'latitude': '37.529987',
   'longitude': '-77.407482',
   'human_address': '{"address": "621 Chimborazo Blvd\\nRichmond, VA\\n(37.529987, -77.407482)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18025411',
  '326.13'],
 [{'latitude': '37.476554',
   'longitude': '-77.439674',
   'human_address': '{"address": "2408 Lamberts Ave\\nRichmond, VA\\n(37.476554, -77.439674)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19053956',
  '895.98'],
 [{'latitude': '37.515928',
   'longitude': '-77.453852',
   'human_address': '{"address": "2301 Rear Wise St\\nRichmond, VA\\n(37.515928, -77.453852)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '28253',
  '157.13'],
 [{'latitude': '37.532281',
   'longitude': '-77.399352',
   'human_address': '{"address": "1312 N 36th St\\nRichmond, VA\\n(37.532281, -77.399352)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '925536',
  '60.24'],
 [{'latitude': '37.475043',
   'longitude': '-77.481561',
   'human_address': '{"address": "3015 Broad Rock Blvd\\nRichmond, VA\\n(37.475043, -77.481561)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18014541',
  '1198.19'],
 [{'latitude': '37.514205',
   'longitude': '-77.446058',
   'human_address': '{"address": "1813 Maury St\\nRichmond, VA\\n(37.514205, -77.446058)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '929816',
  '335.70'],
 [{'latitude': '37.464102',
   'longitude': '-77.453653',
   'human_address': '{"address": "3036 Dupont Ave\\nRichmond, VA\\n(37.464102, -77.453653)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '16018783',
  '1089.54'],
 [{'latitude': '37.546336',
   'longitude': '-77.41482',
   'human_address': '{"address": "1436 Rogers St\\nRichmond, VA\\n(37.546336, -77.41482)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '32527',
  '284.53'],
 [{'latitude': '37.549302',
   'longitude': '-77.400629',
   'human_address': '{"address": "2605 Phaup St\\nRichmond, VA\\n(37.549302, -77.400629)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '10027656',
  '519.84'],
 [{'latitude': '37.511433',
   'longitude': '-77.396974',
   'human_address': '{"address": "1509 Winchell St\\nRichmond, VA\\n(37.511433, -77.396974)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '136993',
  '476.41'],
 [{'latitude': '37.499682',
   'longitude': '-77.475764',
   'human_address': '{"address": "804 Bedrock Lane\\nRichmond, VA\\n(37.499682, -77.475764)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '17009967',
  '662.53'],
 [{'latitude': '37.514934',
   'longitude': '-77.449676',
   'human_address': '{"address": "120 E 21st St\\nRichmond, VA\\n(37.514934, -77.449676)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '91774',
  '1832.77'],
 [{'latitude': '37.562868',
   'longitude': '-77.433239',
   'human_address': '{"address": "2204 North Ave\\nRichmond, VA\\n(37.562868, -77.433239)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '13031368',
  '83.29'],
 [{'latitude': '37.54515',
   'longitude': '-77.588377',
   'human_address': '{"address": "3617 Wainfleet Dr\\nRichmond, VA\\n(37.54515, -77.588377)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '17002499',
  '3534.86'],
 [{'latitude': '37.51815',
   'longitude': '-77.444876',
   'human_address': '{"address": "118 Lipscomb St\\nRichmond, VA\\n(37.51815, -77.444876)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '929649',
  '335.70'],
 [{'latitude': '37.528566',
   'longitude': '-77.517996',
   'human_address': '{"address": "6620 Greenvale Dr\\nRichmond, VA\\n(37.528566, -77.517996)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '13006508',
  '297.54'],
 [{'latitude': '37.483523',
   'longitude': '-77.495647',
   'human_address': '{"address": "5612 Heywood Road\\nRichmond, VA\\n(37.483523, -77.495647)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '16013814',
  '1654.61'],
 [{'latitude': '37.533394',
   'longitude': '-77.430583',
   'human_address': '{"address": "1510 E CARY ST\\nRichmond, VA\\n(37.533394, -77.430583)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '66151',
  '902.18'],
 [{'latitude': '37.521562',
   'longitude': '-77.507179',
   'human_address': '{"address": "1306 Newell Road\\nRichmond, VA\\n(37.521562, -77.507179)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '31171',
  '360.87'],
 [{'latitude': '37.555403',
   'longitude': '-77.44137',
   'human_address': '{"address": "711 Mitchell St\\nRichmond, VA\\n(37.555403, -77.44137)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '117446',
  '132.80'],
 [{'latitude': '37.520849',
   'longitude': '-77.450123',
   'human_address': '{"address": "223 Cowardin Ave\\nRichmond, VA\\n(37.520849, -77.450123)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18044475',
  '97.80'],
 [{'latitude': '37.477319',
   'longitude': '-77.440756',
   'human_address': '{"address": "3401 Lynhaven Ave\\nRichmond, VA\\n(37.477319, -77.440756)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '15053340',
  '520.72'],
 [{'latitude': '37.514456',
   'longitude': '-77.452207',
   'human_address': '{"address": "2311 Short Decatur St\\nRichmond, VA\\n(37.514456, -77.452207)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19045841',
  '180.57'],
 [{'latitude': '37.571564',
   'longitude': '-77.434126',
   'human_address': '{"address": "105 W Brookland Park Blvd\\nRichmond, VA\\n(37.571564, -77.434126)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19034917',
  '2869.27'],
 [{'latitude': '37.550292',
   'longitude': '-77.408638',
   'human_address': '{"address": "2015 Selden St\\nRichmond, VA\\n(37.550292, -77.408638)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '15028885',
  '194.27'],
 [{'latitude': '37.583359',
   'longitude': '-77.434869',
   'human_address': '{"address": "3716 Rear Westcliffe Ave\\nRichmond, VA\\n(37.583359, -77.434869)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19042003',
  '193.48'],
 [{'latitude': '37.51165',
   'longitude': '-77.395234',
   'human_address': '{"address": "5218 Parker St\\nRichmond, VA\\n(37.51165, -77.395234)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18027909',
  '448.85'],
 [{'latitude': '37.529796',
   'longitude': '-77.400627',
   'human_address': '{"address": "3810 P St\\nRichmond, VA\\n(37.529796, -77.400627)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '925652',
  '87.57'],
 [{'latitude': '37.476462',
   'longitude': '-77.437876',
   'human_address': '{"address": "3426 Keighly Road\\nRichmond, VA\\n(37.476462, -77.437876)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19053803',
  '641.04'],
 [{'latitude': '37.517167',
   'longitude': '-77.454514',
   'human_address': '{"address": "2220 Bainbridge St\\nRichmond, VA\\n(37.517167, -77.454514)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '16045616',
  '217.27'],
 [{'latitude': '37.579868',
   'longitude': '-77.424343',
   'human_address': '{"address": "507 Patrick Ave\\nRichmond, VA\\n(37.579868, -77.424343)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '18038972',
  '284.90'],
 [{'latitude': '37.543136',
   'longitude': '-77.407853',
   'human_address': '{"address": "1601 N 25th St\\nRichmond, VA\\n(37.543136, -77.407853)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '16024592',
  '1107.17'],
 [{'latitude': '37.595251',
   'longitude': '-77.450504',
   'human_address': '{"address": "4513 E Seminary Ave\\nRichmond, VA\\n(37.595251, -77.450504)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19203416',
  '380.24'],
 [{'latitude': '37.553704',
   'longitude': '-77.420009',
   'human_address': '{"address": "2100 A Whitcomb St\\nRichmond, VA\\n(37.553704, -77.420009)", "city": "Richmond", "state": "VA", "zip": ""}'},
  '19024997',
  '2017.49']]

In [53]:
crime_df = pd.read_csv("C:\\Users\\AFCummings\\git\\Project2RiotGamesData\\Resources\\Crime Information.csv")
column_list = list(crime_df)
column_list.remove("NEIGHBORHOOD_NAME")
column_list.remove("Lat")
column_list.remove("Long")
print(column_list)
crime_df["sum"] = crime_df[column_list].sum(axis=1)
crime_df

['HOMICIDE', 'SEX_OFFENSE', 'ROBBERY', 'ASSAULT', 'BURGLARY', 'VICE', 'THEFT', 'VEH_THEFT', 'OTHER']

,NEIGHBORHOOD_NAME,HOMICIDE,SEX_OFFENSE,ROBBERY,ASSAULT,BURGLARY,VICE,THEFT,VEH_THEFT,OTHER,Lat,Long,sum
0,ANCAROWS LANDING,0,0,0,0,0,7,3,0,25,37.519000,-77.420800,35
1,BEAUFONT,0,0,0,8,4,1,7,4,58,37.510800,-77.511800,82
2,BELLE AND MAYO ISLANDS,0,2,1,1,0,8,7,2,48,37.530600,-77.451600,69
3,BELLEMEADE,0,2,6,92,33,36,89,25,351,37.499000,-77.438600,634
4,BELLEVUE,0,1,0,5,3,0,63,4,59,37.590800,-77.457600,135
5,BELMONT WOODS,0,0,1,2,2,0,2,1,6,37.467300,-77.497400,14
6,BELT CENTER,0,2,2,31,14,23,170,26,290,37.504800,-77.480200,558
7,BIOTECH AND MCV DISTRICT,0,0,0,7,0,6,27,1,63,37.543500,-77.430800,104
8,BLACKWELL,0,4,7,76,14,53,104,21,352,37.516600,-77.442900,631
9,BRAUERS,0,0,3,19,1,11,27,13,86,37.546800,-77.413500,160
10,BRITISH CAMP FARMS,1,0,10,30,12,11,46,6,129,37.475300,-77.474500,245
11,BROAD ROCK,3,2,6,59,27,49,75,20,262,37.505000,-77.463700,503
12,BROAD ROCK INDUSTRIAL PARK,0,0,0,5,4,1,10,0,28,NaN,NaN,48
13,BROAD ROCK SPORTS COMPLEX,0,0,0,4,0,2,2,0,9,37.484900,-77.483800,17
14,BROOKBURY,0,1,0,2,0,0,2,2,17,37.464000,-77.491700,24
15,BROOKHAVEN FARMS,0,1,3,11,9,1,10,3,28,37.476700,-77.511800,66
16,BROOKLAND PARK,1,1,3,27,6,22,35,10,140,37.575700,-77.431500,245
17,BRYAN PARK,0,0,0,1,1,1,3,0,13,37.596400,-77.472600,19
18,BYRD PARK,0,1,2,8,9,4,15,2,58,37.544700,-77.473100,99
19,CAPITOL DISTRICT,0,0,2,11,0,6,19,2,160,37.537900,-77.433100,200
20,CARILLON,0,0,1,6,0,0,8,1,41,37.539600,-77.486000,57
21,CARVER,0,2,6,34,8,14,121,10,275,37.553900,-77.448700,470
22,CARYTOWN,0,1,7,24,10,7,106,2,197,37.553100,-77.483800,354
23,CEDARHURST,1,1,1,33,11,3,48,24,104,37.523000,-77.503200,226
24,CENTRAL OFFICE,0,1,1,10,0,1,21,4,89,37.536400,-77.437900,127
25,CHAMBERLAYNE INDUSTRIAL CENTER,0,0,5,32,4,28,83,10,199,37.559400,-77.442500,361
26,CHERRY GARDENS,0,0,0,2,1,1,5,0,12,37.482200,-77.459400,21
27,CHIMBORAZO,0,2,1,11,6,6,34,8,60,37.528300,-77.405600,128
28,CHIPPENHAM FOREST,0,4,3,54,5,18,117,14,145,37.532000,-77.537600,360
29,CHURCH HILL,0,1,6,16,10,7,68,22,148,37.532800,-77.416300,278
...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,STADIUM,0,0,0,6,1,0,4,0,9,37.550400,-77.488800,20
114,STONEWALL COURT,0,0,0,0,0,0,5,1,3,37.570900,-77.508900,9
115,STONY POINT,0,0,0,4,2,1,15,2,47,37.549291,-77.564808,71
116,STRATFORD HILLS,1,0,0,3,6,6,36,2,65,37.550900,-77.530400,119
117,SWANSBORO,3,3,17,56,22,47,163,15,362,37.516600,-77.455900,688
118,SWANSBORO WEST,1,0,9,56,27,28,88,13,281,37.506500,-77.471600,503
119,SWANSON,0,0,5,12,8,8,51,8,112,NaN,NaN,204
120,THE DIAMOND,0,1,3,24,1,19,46,9,175,37.571800,-77.463500,278
121,THE FAN,3,14,20,125,64,28,422,59,813,37.551300,-77.458800,1548
122,THE MUSEUM DISTRICT,0,6,2,32,13,3,119,20,288,37.561700,-77.480900,483
123,THREE CHOPT,0,0,1,7,3,1,13,1,72,37.577600,-77.526400,98
124,UNION HILL,2,1,10,56,11,37,88,15,231,37.537700,-77.420000,451
125,UPPER SHOCKOE VALLEY,0,2,0,26,3,12,36,7,215,37.543600,-77.425700,301
126,VCU,0,0,2,23,3,4,41,2,133,37.548300,-77.452700,208
127,VIRGINIA UNION,0,1,6,30,9,74,62,7,250,37.568500,-77.450100,439
128,WALMSLEY,0,1,5,46,18,8,43,5,131,37.465900,-77.460200,257
129,WARWICK,0,1,0,10,2,2,4,3,42,37.459000,-77.422800,64
130,WASHINGTON PARK,0,0,3,24,1,10,16,2,76,37.589700,-77.440100,132
131,WESTHAMPTON,0,0,0,6,2,0,11,2,45,37.574100,-77.514600,66
132,WESTLAKE HILLS,0,0,0,6,0,2,19,4,36,37.529500,-77.514600,67
133,WESTOVER HILLS,1,0,4,55,17,15,83,21,175,37.529700,-77.491700,371
134,WHITCOMB,3,0,8,142,15,55,72,27,401,37.553008,-77.417968,723
135,WILLOW LAWN,0,0,0,3,0,0,13,3,19,37.572300,-77.497400,38
136,WILLOW OAKS,0,0,0,0,3,0,4,2,7,37.537900,-77.507500,16
137,WILTON,1,0,0,0,3,0,3,2,12,37.560100,-77.518900,21
138,WINDSOR,0,0,2,8,4,0,22,2,46,37.550100,-77.498900,84
139,WOODHAVEN,0,2,2,18,9,2,26,5,68,37.497900,-77.488800,132
140,WOODLAND HEIGHTS,0,1,3,23,13,7,83,11,141,37.521300,-77.463000,282
141,WOODVILLE,0,0,3,15,4,26,13,6,96,37.543100,-77.403500,163
142,WORTHINGTON,0,0,0,13,3,2,8,3,56,37.491300,-77.513200,85

In [54]:
crime_df = crime_df.drop(crime_df.columns[[0,1,2,3,4,5,6,7,8,9]], axis = 1)
crime_df

           Lat       Long   sum
0    37.519000 -77.420800    35
1    37.510800 -77.511800    82
2    37.530600 -77.451600    69
3    37.499000 -77.438600   634
4    37.590800 -77.457600   135
5    37.467300 -77.497400    14
6    37.504800 -77.480200   558
7    37.543500 -77.430800   104
8    37.516600 -77.442900   631
9    37.546800 -77.413500   160
10   37.475300 -77.474500   245
11   37.505000 -77.463700   503
12         NaN        NaN    48
13   37.484900 -77.483800    17
14   37.464000 -77.491700    24
15   37.476700 -77.511800    66
16   37.575700 -77.431500   245
17   37.596400 -77.472600    19
18   37.544700 -77.473100    99
19   37.537900 -77.433100   200
20   37.539600 -77.486000    57
21   37.553900 -77.448700   470
22   37.553100 -77.483800   354
23   37.523000 -77.503200   226
24   37.536400 -77.437900   127
25   37.559400 -77.442500   361
26   37.482200 -77.459400    21
27   37.528300 -77.405600   128
28   37.532000 -77.537600   360
29   37.532800 -77.416300   278
..         ...        ...   ...
113  37.550400 -77.488800    20
114  37.570900 -77.508900     9
115  37.549291 -77.564808    71
116  37.550900 -77.530400   119
117  37.516600 -77.455900   688
118  37.506500 -77.471600   503
119        NaN        NaN   204
120  37.571800 -77.463500   278
121  37.551300 -77.458800  1548
122  37.561700 -77.480900   483
123  37.577600 -77.526400    98
124  37.537700 -77.420000   451
125  37.543600 -77.425700   301
126  37.548300 -77.452700   208
127  37.568500 -77.450100   439
128  37.465900 -77.460200   257
129  37.459000 -77.422800    64
130  37.589700 -77.440100   132
131  37.574100 -77.514600    66
132  37.529500 -77.514600    67
133  37.529700 -77.491700   371
134  37.553008 -77.417968   723
135  37.572300 -77.497400    38
136  37.537900 -77.507500    16
137  37.560100 -77.518900    21
138  37.550100 -77.498900    84
139  37.497900 -77.488800   132
140  37.521300 -77.463000   282
141  37.543100 -77.403500   163
142  37.491300 -77.513200    85

[143 rows x 3 columns]

In [55]:
crime_df.dropna()

           Lat       Long   sum
0    37.519000 -77.420800    35
1    37.510800 -77.511800    82
2    37.530600 -77.451600    69
3    37.499000 -77.438600   634
4    37.590800 -77.457600   135
5    37.467300 -77.497400    14
6    37.504800 -77.480200   558
7    37.543500 -77.430800   104
8    37.516600 -77.442900   631
9    37.546800 -77.413500   160
10   37.475300 -77.474500   245
11   37.505000 -77.463700   503
13   37.484900 -77.483800    17
14   37.464000 -77.491700    24
15   37.476700 -77.511800    66
16   37.575700 -77.431500   245
17   37.596400 -77.472600    19
18   37.544700 -77.473100    99
19   37.537900 -77.433100   200
20   37.539600 -77.486000    57
21   37.553900 -77.448700   470
22   37.553100 -77.483800   354
23   37.523000 -77.503200   226
24   37.536400 -77.437900   127
25   37.559400 -77.442500   361
26   37.482200 -77.459400    21
27   37.528300 -77.405600   128
28   37.532000 -77.537600   360
29   37.532800 -77.416300   278
30   37.536500 -77.408500   480
..         ...        ...   ...
112  37.492000 -77.483100   505
113  37.550400 -77.488800    20
114  37.570900 -77.508900     9
115  37.549291 -77.564808    71
116  37.550900 -77.530400   119
117  37.516600 -77.455900   688
118  37.506500 -77.471600   503
120  37.571800 -77.463500   278
121  37.551300 -77.458800  1548
122  37.561700 -77.480900   483
123  37.577600 -77.526400    98
124  37.537700 -77.420000   451
125  37.543600 -77.425700   301
126  37.548300 -77.452700   208
127  37.568500 -77.450100   439
128  37.465900 -77.460200   257
129  37.459000 -77.422800    64
130  37.589700 -77.440100   132
131  37.574100 -77.514600    66
132  37.529500 -77.514600    67
133  37.529700 -77.491700   371
134  37.553008 -77.417968   723
135  37.572300 -77.497400    38
136  37.537900 -77.507500    16
137  37.560100 -77.518900    21
138  37.550100 -77.498900    84
139  37.497900 -77.488800   132
140  37.521300 -77.463000   282
141  37.543100 -77.403500   163
142  37.491300 -77.513200    85

[138 rows x 3 columns]

In [56]:
crime_list = crime_df.values.tolist()

In [80]:
crime_by_type = pd.read_csv("C:\\Users\\AFCummings\\git\\Project2RiotGamesData\\Resources\\Crime Information.csv")

In [81]:
crime_by_type = crime_by_type.drop(crime_by_type.columns[[0,10,11]], axis=1)
crime_by_type

,HOMICIDE,SEX_OFFENSE,ROBBERY,ASSAULT,BURGLARY,VICE,THEFT,VEH_THEFT,OTHER
0,0,0,0,0,0,7,3,0,25
1,0,0,0,8,4,1,7,4,58
2,0,2,1,1,0,8,7,2,48
3,0,2,6,92,33,36,89,25,351
4,0,1,0,5,3,0,63,4,59
5,0,0,1,2,2,0,2,1,6
6,0,2,2,31,14,23,170,26,290
7,0,0,0,7,0,6,27,1,63
8,0,4,7,76,14,53,104,21,352
9,0,0,3,19,1,11,27,13,86
10,1,0,10,30,12,11,46,6,129
11,3,2,6,59,27,49,75,20,262
12,0,0,0,5,4,1,10,0,28
13,0,0,0,4,0,2,2,0,9
14,0,1,0,2,0,0,2,2,17
15,0,1,3,11,9,1,10,3,28
16,1,1,3,27,6,22,35,10,140
17,0,0,0,1,1,1,3,0,13
18,0,1,2,8,9,4,15,2,58
19,0,0,2,11,0,6,19,2,160
20,0,0,1,6,0,0,8,1,41
21,0,2,6,34,8,14,121,10,275
22,0,1,7,24,10,7,106,2,197
23,1,1,1,33,11,3,48,24,104
24,0,1,1,10,0,1,21,4,89
25,0,0,5,32,4,28,83,10,199
26,0,0,0,2,1,1,5,0,12
27,0,2,1,11,6,6,34,8,60
28,0,4,3,54,5,18,117,14,145
29,0,1,6,16,10,7,68,22,148
...,...,...,...,...,...,...,...,...,...
113,0,0,0,6,1,0,4,0,9
114,0,0,0,0,0,0,5,1,3
115,0,0,0,4,2,1,15,2,47
116,1,0,0,3,6,6,36,2,65
117,3,3,17,56,22,47,163,15,362
118,1,0,9,56,27,28,88,13,281
119,0,0,5,12,8,8,51,8,112
120,0,1,3,24,1,19,46,9,175
121,3,14,20,125,64,28,422,59,813
122,0,6,2,32,13,3,119,20,288
123,0,0,1,7,3,1,13,1,72
124,2,1,10,56,11,37,88,15,231
125,0,2,0,26,3,12,36,7,215
126,0,0,2,23,3,4,41,2,133
127,0,1,6,30,9,74,62,7,250
128,0,1,5,46,18,8,43,5,131
129,0,1,0,10,2,2,4,3,42
130,0,0,3,24,1,10,16,2,76
131,0,0,0,6,2,0,11,2,45
132,0,0,0,6,0,2,19,4,36
133,1,0,4,55,17,15,83,21,175
134,3,0,8,142,15,55,72,27,401
135,0,0,0,3,0,0,13,3,19
136,0,0,0,0,3,0,4,2,7
137,1,0,0,0,3,0,3,2,12
138,0,0,2,8,4,0,22,2,46
139,0,2,2,18,9,2,26,5,68
140,0,1,3,23,13,7,83,11,141
141,0,0,3,15,4,26,13,6,96
142,0,0,0,13,3,2,8,3,56

In [82]:
#def sum_columns(column_name):
    #crime_by_type.loc['Total'] = pd.Series(crime_by_type[f"{column_name}"].sum(), index = [f"{column_name}"])
#sum_columns('HOMICIDE')
#sum_columns('SEX_OFFENSE')
#sum_columns('ROBBERY')
#sum_columns('ASSAULT')
#sum_columns('BURGLARY')
#sum_columns('VICE')
#sum_columns('THEFT')
#sum_columns('VEH_THEFT')
#sum_columns('OTHER')
def crime_sum_type(column_name, new_column):
    crime_by_type[f"{new_column}"] = crime_by_type[f"{column_name}"].sum(axis=0)
crime_sum_type('HOMICIDE', 'homicide_tot')
crime_sum_type('SEX_OFFENSE', 'sex_off_total')
crime_sum_type('ROBBERY', 'rob_total')
crime_sum_type('ASSAULT', 'assault_tot')
crime_sum_type('BURGLARY', 'burglary_tot')
crime_sum_type('VICE', 'vice_tot')
crime_sum_type('THEFT', 'theft_tot')
crime_sum_type('VEH_THEFT', 'veh_theft_tot')
crime_sum_type('OTHER', 'other_tot')

In [84]:
crime_by_type
crime_by_type = crime_by_type[['homicide_tot','sex_off_total','rob_total','assault_tot','burglary_tot','vice_tot','theft_tot',
                              'veh_theft_tot','other_tot']]

In [88]:
crime_by_type = crime_by_type[:1]
crime_by_type

,homicide_tot,sex_off_total,rob_total,assault_tot,burglary_tot,vice_tot,theft_tot,veh_theft_tot,other_tot
0,62,175,442,3932,1030,1882,6509,1226,19550

In [ ]:
crime_type_list = crime_by_type.values.tolist()

In [104]:
crime2017 = pd.read_csv("C:\\Users\\AFCummings\\git\\Project2RiotGamesData\\Resources\\Crime Information2017-2018.csv")

In [105]:
crime2017 = crime2017.drop(crime2017.columns[[0]], axis=1)
crime2017

,HOMICIDE,SEX_OFFENSE,ROBBERY,ASSAULT,BURGLARY,VICE,THEFT,VEH_THEFT,OTHER
0,0,0,1,0,0,5,4,0,16
1,0,0,0,10,4,6,12,9,46
2,0,0,0,6,0,3,5,0,38
3,2,1,9,109,28,47,90,47,375
4,0,1,0,5,5,5,31,8,54
5,0,0,1,6,0,0,2,3,10
6,2,4,4,41,4,27,171,37,288
7,0,0,0,7,3,3,15,0,89
8,0,3,8,69,10,27,91,18,224
9,0,0,3,11,7,19,22,5,73
10,2,3,5,50,8,13,53,6,155
11,3,4,10,66,15,48,74,17,266
12,0,0,0,3,1,0,11,2,39
13,0,0,1,3,0,4,3,0,13
14,0,0,0,4,1,3,13,2,20
15,0,2,0,7,2,0,6,2,30
16,1,0,6,38,14,19,36,14,177
17,0,0,0,1,0,0,1,0,10
18,0,0,0,8,7,4,33,3,73
19,0,1,1,20,1,2,17,6,191
20,0,0,0,2,0,1,19,2,26
21,1,3,3,30,12,14,108,11,282
22,0,0,5,23,16,3,92,7,231
23,0,0,1,27,17,4,40,22,93
24,0,1,0,7,1,0,22,2,101
25,0,0,4,28,8,50,49,7,209
26,0,0,1,4,1,1,6,1,15
27,0,0,2,13,4,4,44,17,81
28,1,5,2,56,0,15,113,7,142
29,0,0,5,17,8,12,78,14,132
...,...,...,...,...,...,...,...,...,...
118,0,1,5,83,17,39,172,18,350
119,4,4,7,96,30,30,111,16,302
120,0,0,4,27,10,7,58,6,94
121,0,1,1,14,1,8,37,9,144
122,0,12,19,140,70,17,503,71,923
123,0,4,6,29,17,7,100,24,275
124,0,0,2,2,1,2,20,4,68
125,0,1,5,51,7,33,80,10,231
126,0,0,0,0,0,0,0,0,2
127,0,2,4,19,2,17,24,2,244
128,0,1,0,13,4,8,38,3,140
129,0,1,4,32,17,71,60,13,185
130,0,5,2,37,11,7,25,5,110
131,0,0,0,11,1,1,5,3,29
132,1,2,3,35,5,22,25,9,97
133,0,0,1,4,1,2,9,6,41
134,1,0,0,8,1,2,10,3,34
135,3,2,6,49,34,10,49,12,148
136,0,0,1,2,1,0,18,5,38
137,0,0,1,0,0,0,3,0,12
138,4,2,8,128,35,81,38,17,372
139,0,1,0,2,1,0,15,3,28
140,0,0,0,1,1,0,6,0,5
141,0,0,0,0,0,0,5,2,16
142,0,0,16,9,9,4,20,8,44
143,0,0,0,1,2,0,14,2,23
144,0,1,2,10,6,3,32,0,55
145,0,0,1,15,9,17,94,19,132
146,0,0,1,22,5,12,13,6,82
147,0,0,0,7,3,2,15,7,43

In [106]:
def crime_2017_type(column_name, new_column):
    crime2017[f"{new_column}"] = crime2017[f"{column_name}"].sum(axis=0)
crime_2017_type('HOMICIDE', 'homicide_tot')
crime_2017_type('SEX_OFFENSE', 'sex_off_total')
crime_2017_type('ROBBERY', 'rob_total')
crime_2017_type('ASSAULT', 'assault_tot')
crime_2017_type('BURGLARY', 'burglary_tot')
crime_2017_type('VICE', 'vice_tot')
crime_2017_type('THEFT', 'theft_tot')
crime_2017_type('VEH_THEFT', 'veh_theft_tot')
crime_2017_type('OTHER', 'other_tot')

In [107]:
crime2017
crime2017 = crime2017[['homicide_tot','sex_off_total','rob_total','assault_tot','burglary_tot','vice_tot','theft_tot',
                              'veh_theft_tot','other_tot']]

In [108]:
crime2017 = crime2017[:1]
crime2017

,homicide_tot,sex_off_total,rob_total,assault_tot,burglary_tot,vice_tot,theft_tot,veh_theft_tot,other_tot
0,57,193,426,4099,1102,2132,6598,1337,19693

In [109]:
crime_2017_list = crime2017.values.tolist()